baseURL = "https://marcbenedi.github.io/blog/"
languageCode = "en-us"
title = "My New Hugo Site"

publishDir = "docs"

theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # set theme to full screen width
  fullWidthTheme = true
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[languages]
  [languages.en]
    title = "Î»"
    subtitle = "marcb's blog"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd ~"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "http://marcb.pro/"
